## Generate simulated data
nY vector[2400]
T [2400,30]
incub[81]
obs[81]

```{r}
library(rjags)
library(HDInterval)
source('./generate_line_lists_zelner.R') 
#ds <- readRDS('../data/data.list.rds')
```


Read in model
```{r}
source('../model/sketch Zelner Model alt.R')
```

```{r}
##############################################################
#Model Fitting
##############################################################
inits1=list(".RNG.seed"=c(123), ".RNG.name"='base::Wichmann-Hill')
inits2=list(".RNG.seed"=c(456), ".RNG.name"='base::Wichmann-Hill')
inits3=list(".RNG.seed"=c(789), ".RNG.name"='base::Wichmann-Hill')



##############################################
#Model Organization
##############################################
model_spec<-textConnection(zelner_jags2)
model_jags<-jags.model(model_spec, 
                       inits=list(inits1,inits2, inits3),
                       data=list('N.HH'=N.HH,
                                 'N.hh.members'=N.hh.members,
                                 'infected_matrix'=infected_matrix,
                                 'day.matrix'=day.matrix,
                                  'y' = (1-infected_matrix),
                                 'tmax'=apply(day.matrix,1,max,na.rm=T)
                                 ),
                       n.adapt=10000, 
                       n.chains=3)

```

```{r}
params<-c('alpha',
          'v')

##############################################
#Posterior Sampling
##############################################
posterior_samples<-coda.samples(model_jags, 
                                params, 
                                n.iter=10000)
posterior_samples.all<-do.call(rbind,posterior_samples)

post_means<-apply(posterior_samples.all, 2, median)
sample.labs<-names(post_means)
ci<-t(hdi(posterior_samples.all, credMass = 0.95))
ci<-matrix(sprintf("%.1f",round(ci,1)), ncol=2)
row.names(ci)<-sample.labs
post_means<-sprintf("%.1f",round(post_means,1))
names(post_means)<-sample.labs

alpha.index <- grep('alpha',sample.labs)
v.index <- grep('v',sample.labs)

ci[alpha.index,]
ci[v.index,]



```



