## Generate simulated data
nY vector[2400]
T [2400,30]
incub[81]
obs[81]

```{r}
library(rjags)
library(HDInterval)
source('./generate_simdata_exposuretime_DMW2.R') 
#source('./generate_line_lists_zelner.R') 
#ds <- readRDS('../data/data.list.rds')
```


```{r}
N.samples <- 10
hh_df_rep <- hh_df[rep(1:nrow(hh_df), times = N.samples),]
hh_df_rep$iter <- rep(1:N.samples, each = nrow(hh_df))
```



## d_jk(t) definition -- this first part can be computed out of JAGS

```{r}


## Define latent distributions
# Hyperpriors for the latent distributions
# parameterized by mode (m) and standard deviation (sd):
m1 <- runif(N.samples,2,6)
sd1 <- runif(N.samples,2,3) 
ra1 <- ( m1 + sqrt( m1^2 + 4*sd1^2 ) ) / ( 2 * sd1^2 )
sh1 <- 1 + m1 * ra1

m2 <- runif(N.samples, 2,6)
sd2 <- runif(N.samples,2,3)
ra2 <- ( m2 + sqrt( m2^2 + 4*sd2^2 ) ) / ( 2 * sd2^2 )
sh2 <- 1 + m2 * ra2

m3 <- runif(N.samples,2,6) #days
sd3 <- runif(N.samples,2,3) #SD on days
ra3 <- ( m3 + sqrt( m3^2 + 4*sd3^2 ) ) / ( 2 * sd3^2 )
sh3 <- 1 + m3 * ra3

day.infectious <- array(NA, dim=c(N.samples,N.HH,max(N.hh.members) ))
day.exposed <- array(NA, dim=c(N.samples,N.HH,max(N.hh.members) ))
day.infectious.end <- array(NA, dim=c(N.samples,N.HH,max(N.hh.members+1) ))
infect.dist <- array(NA, dim=c(N.samples,N.HH,max(N.hh.members+1) ))
expose.dist <- array(NA, dim=c(N.samples,N.HH,max(N.hh.members+1) ))
end.inf  <- array(NA, dim=c(N.samples,N.HH,max(N.hh.members+1) ))

   n.sim <- N.samples*N.HH*max(N.hh.members)
    
   #Generate random draws for duration of infectious, 
    infect.dist <-  
      array(rgamma(n.sim,sh1, ra1), dim=c(N.HH,max(N.hh.members), N.samples)) #duration infectiousness (actually is duration of time from infectiousness to test)
    
    expose.dist <- 
      array(rgamma(n.sim,sh2, ra2), dim=c(N.HH,max(N.hh.members), N.samples)) 
    
    end.inf <-
      array(rgamma(n.sim,sh3,ra3),  dim=c(N.HH,max(N.hh.members), N.samples)) 
    
    max.time.hh <- round(apply(expose.dist,c(1,3),max, na.rm=T) +
      apply(infect.dist,c(1,3),max, na.rm=T) ) +1

       #check
   #  day.infectious <-apply(infect.dist,2, function(x) day.matrix  )
   # day.infectious <- array(day.infectious, dim=c(dim(day.matrix),N.samples ))
   # sum(day.infectious[,,1]== day.matrix, na.rm=T) == sum(!is.na(day.infectious[,,1]))
    
   day.infectious <- array(NA, dim=c(dim(day.matrix),N.samples ))
   for(i in 1:N.samples){
      day.infectious[,,i] <- day.matrix - infect.dist[,,i]
   }
   
    for(i in 1:N.samples){
      for(j in 1:dim(day.infectious)[1]){
        day.infectious[j,,i] <- day.infectious[j,,i] + max.time.hh[j,i]

      }
    }
   

   #for each hh set t=1 to be first
   last.day.infect.hh <- apply(round(day.infectious + end.inf), c(1,3), max, na.rm=T)
   first.day.infect.hh <- round(apply(day.infectious - expose.dist , c(1,3), min, na.rm=T))
   
  for(i in 1:N.samples){
     day.infectious[,,i] <- t(apply(day.infectious[,,i],1, function(x){
       z <- round(x) #- min(x, na.rm=T)  
       return(z)
     }))
   }
 #  View(day.infectious[,,1])
   
   
    day.exposed <-  
      round(day.infectious - expose.dist) +3  #latent period (t_infect in the document)
    
    day.infectious.end <- 
      round(day.infectious + end.inf) #how long infectious after onset of infectiousness
    
    #i,10000 matrix
    time.study.HH <- matrix(NA, nrow=dim(day.infectious.end)[1], N.samples)
    for( i in 1:N.samples){
      max.hh.time <- apply(day.infectious.end[,,i],1, max, na.rm=T)
      min.hh.time <- apply(day.exposed[,,i],1, min, na.rm=T)
          time.study.HH[,i] <- max.hh.time - min.hh.time +1
    }
    
    time.study.HH <- round(time.study.HH+20)
    
    
    #
    
    
```

Read in model
```{r}
source('../model/chain_binomial_test_separate.R')
```

```{r}
##############################################################
#Model Fitting
##############################################################
inits1=list(".RNG.seed"=c(123), ".RNG.name"='base::Wichmann-Hill')
inits2=list(".RNG.seed"=c(456), ".RNG.name"='base::Wichmann-Hill')
inits3=list(".RNG.seed"=c(789), ".RNG.name"='base::Wichmann-Hill')



##############################################
#Model Organization
##############################################
model_spec<-textConnection(chain_binomial_jags)
model_jags<-jags.model(model_spec, 
                       #inits=list(inits1,inits2, inits3),
                       inits=list(inits1),

                                 data=list('N.HH'=N.HH,
                                 'vaxdose1'=vax,                                                       #'vaxdose2'=vaxdose2,
                                 'N.hh.members'=N.hh.members,
                                 'day.infectious'=day.infectious,
                                 'day.exposed'=day.exposed,
                                 'day.infectious.end'=day.infectious.end,
                                 'y' = (1-infected_matrix),
                                 'y2' = (1-infected_matrix),
                                                                  'selecter1'=1,
                                 'time.study.HH'=time.study.HH
                                 #'tmax'=apply(day.matrix,1,max,na.rm=T)
                                 ),
                       n.adapt=10000, 
                       
                       n.chains=1)

```

```{r}
params<-c('alpha0',
          'delta0',
          'beta1',
          'beta2',
          'kappa1',
          'kappa2')

##############################################
#Posterior Sampling
##############################################
posterior_samples<-coda.samples(model_jags, 
                                params, 
                                n.iter=10000)
posterior_samples.all<-do.call(rbind,posterior_samples)

post_means<-apply(posterior_samples.all, 2, median)
sample.labs<-names(post_means)
ci<-t(hdi(posterior_samples.all, credMass = 0.95))
ci<-matrix(sprintf("%.1f",round(ci,1)), ncol=2)
row.names(ci)<-sample.labs
post_means<-sprintf("%.1f",round(post_means,1))
names(post_means)<-sample.labs

alpha.index <- grep('alpha',sample.labs)
beta.index <- grep('beta1',sample.labs)
kappa.index <- grep('kappa1',sample.labs)
delta.index <- grep('delta',sample.labs)


ci[alpha.index,]
ci[beta.index,]
ci[kappa.index,]
ci[delta.index,]


#Test combo of beta and kappa

beta_kappa <- 
  posterior_samples.all[,beta.index] + posterior_samples.all[,kappa.index]
hist(beta_kappa)
```



