---
title: "sim_data_model"
author: "Dan Weinberger"
date: "2/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rjags)

```

## Generate simulated data
nY vector[2013]  0= infected; 1=uninfected
T [2013,38,5]
incub[81]
obs[81]

```{r}
source('./generate_data_Ginnycode.R')
ds <- readRDS('../winbugs_PS/data.list.rds')
data.sim <- gen_sim_data()

T <- data.sim$T  #These dimensions not right!

T <- array(T,dim=c(2400,38,1))

#T <- data.list$T
nY <- data.sim$nY
N_infected <- length(nY) - sum(nY)
N_uninfected <- sum(nY)
uninfected_indices <- which(nY==1)
infected_indices <- which(nY==0)

#Obs and incub from the observed data
obs <- ds$obs
incub <- ds$incub
```


Read in model
```{r}
source('../model/Pitzer_annotated_jags.R')
```

```{r}
##############################################################
#Model Fitting
##############################################################
inits1=list(".RNG.seed"=c(123), ".RNG.name"='base::Wichmann-Hill')
inits2=list(".RNG.seed"=c(456), ".RNG.name"='base::Wichmann-Hill')
inits3=list(".RNG.seed"=c(789), ".RNG.name"='base::Wichmann-Hill')



##############################################
#Model Organization
##############################################
model_spec<-textConnection(model_string)
model_jags<-jags.model(model_spec, 
                       inits=list(inits1,inits2, inits3),
                       data=list('T'=T,
                                 'nY'=nY,
                                  'N_contacts'=length(nY),
                                 'N_index_cases' =dim(T)[3] ,
                                 "N_times"= dim(T)[2],
                                 'infected_indices'=infected_indices,
                                 'N_infected'=length(infected_indices),
                                 'N_uninfected'=length(uninfected_indices),
                                 'uninfected_indices'=uninfected_indices,
                                 'obs'=as.vector(obs),
                                 'incub'=incub),
                       n.adapt=10000, 
                       n.chains=3)

```

```{r}
params<-c('p',
          'a',
          'b')

##############################################
#Posterior Sampling
##############################################
posterior_samples<-coda.samples(model_jags, 
                                params, 
                                n.iter=100000)
posterior_samples.all<-do.call(rbind,posterior_samples)

```


