---
title: "Zelner model"
author: "Ottavia Prunas and Dan Weinberger"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(abind)
library(rjags)
library(HDInterval)
library(R.matlab)
```


```{r}
# Read a .mat file
library(R.matlab)
mydata <- readMat(con="../data/EMD538_2020_Lab7.mat")
names(mydata) # tinfect, hh.incidence, hh.size, S, I, E, R
attach(mydata)
```

#------------------------------------------------------------------------------#
# Explore the data
#------------------------------------------------------------------------------#

# EMD538_2020_Lab7.mat: 

# 50 households of varying size exposed to a norovirus-infected family member
```{r}
# Size of household
hh.size
summary(as.vector(hh.size))
hh.size[,50] # 11 people in Household 50

# Time (in hours) at which infection events occurred in household j
tinfect
tinfect[,50] # Among 11 people in Household 50, 3 people got infected from the 
# primary case at Hour 14, 94, and 144. The remaining 8 people 
# escaped infection during the observation period

# Number of people in S, E, I, and R
dim(S) # 504 hours and 50 households
dim(I) # 504 hours and 50 households
# Data on Hour 24-48 in Household 7 & 11
S[c(24:48),c(7,11)]
E[c(24:48),c(7,11)]
I[c(24:48),c(7,11)]
R[c(24:48),c(7,11)]

tmax = dim(S)[1]
S0 = S[1,] # Initial number of susceptibles in each household
Sf = S[tmax,] # Final number of susceptibles in each household
ninfect = S0 - Sf # number infected in each household 

```

```{r}
#------------------------------------------------------------------------------#
# 1. Use maximum likelihood (by minimizing the neg log-likelihood, calculated in 
#    “hhsirLL”) to estimate β as the rate of transmission per day.
#------------------------------------------------------------------------------#

# First, load a function hhsirLL()
# This function uses Zelner's equation to calculate likelihood (Slide 16-17)
# setwd("~/Desktop/EMD538/Lab/Lab7") # <--- Change it to your folder
source(file="EMD538_2020_Lab7_hhsirLL.R")

# Estimate beta (= the rate of transmission per day) by minimizing the neg log-
# likelihood
betaHHest <- optimize(f=hhsirLL,S=S,I=I,tinfect=tinfect, interval=c(0,10))$minimum
betaHHest
```

```{r}
source('zelner_jags.R')
```

```{r}
##############################################################
#Model Fitting
##############################################################
inits1=list(".RNG.seed"=c(123), ".RNG.name"='base::Wichmann-Hill')
inits2=list(".RNG.seed"=c(456), ".RNG.name"='base::Wichmann-Hill')
inits3=list(".RNG.seed"=c(789), ".RNG.name"='base::Wichmann-Hill')


##############################################
#Model Organization
##############################################
model_spec<-textConnection(zelner_jags)
model_jags<-jags.model(model_spec, 
                       inits=list(inits1,inits2, inits3),
                       data=list('I'=I,
                                 'S'=S,
                                 'Sf'=Sf,
                                 'ninfect'=ninfect,
                                 'hh'=dim(S)[2],
                                 'hh.size'= hh.size,
                                 'tmax'= dim(S)[1],
                                 'tinfect'=tinfect,
                                 'dt'=1/24
                                 ),
                       n.adapt=10000, 
                       n.chains=3)

```


```{r}
detach(mydata)
```























